version: '${POSTGRES_VERSION}'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
    ports:
      - '5432:5432'
